"""
VRM response -> shared schema processor
========================================
Takes raw responses from fetch.py and writes them as data.json + history.json
+ hourly_history.json in the same shape every other platform produces, so
the fleet dashboard and per-site dashboards consume them identically.

Field mapping (VRM attribute codes -> our schema):
  Pb -> energy.pv          (solar yield / PV production, kWh)
  Pc -> energy.consumption (site consumption, kWh)
  Gc -> energy.import      (grid consumed by site, kWh)
  Gb -> energy.export      (grid generated by site, kWh)
  Bc -> energy.discharge   (battery to consumers, kWh) [VERIFY against real data]
  Bg -> energy.charge      (battery to grid? OR PV to battery? VERIFY)

The battery codes (Bc, Bg) are the uncertain bit. Once a real site lands data,
cross-check against the VRM portal's Energy Flow view to confirm semantics.
The processor handles missing codes gracefully - sites without batteries
won't have Bc/Bg in their response, which becomes zero in our schema.

Powerflow + financial + performance blocks are added the same way as for
FusionSolar - the shared modules don't care which platform produced the data.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Make shared/ importable
_SHARED_DIR = Path(__file__).resolve().parent.parent.parent / "shared"
if str(_SHARED_DIR) not in sys.path:
    sys.path.insert(0, str(_SHARED_DIR))

import powerflow                                  # noqa: E402
from financial import compute_financials          # noqa: E402
from performance import build_performance         # noqa: E402

SAST = timezone(timedelta(hours=2))
HOURLY_HISTORY_DAYS = None     # unlimited - same as FusionSolar
HISTORY_DAYS = 400


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                     encoding="utf-8")


def _sast_now_iso() -> str:
    return datetime.now(tz=SAST).strftime("%Y-%m-%dT%H:%M:%S+02:00")


def _series_to_timed(records: list, sast: bool = True) -> list[dict]:
    """VRM stats records are [[ts_ms, value, min, max], ...].
    Convert to our schema's [{time: 'YYYY-MM-DD HH:MM:SS', value: x}, ...]
    """
    out = []
    for row in records or []:
        if not isinstance(row, list) or len(row) < 2:
            continue
        ts_ms, value = row[0], row[1]
        if ts_ms is None:
            continue
        dt = datetime.fromtimestamp(ts_ms / 1000, tz=SAST if sast else timezone.utc)
        out.append({
            "time": dt.strftime("%Y-%m-%d %H:%M:%S"),
            "value": float(value) if value is not None else 0.0,
        })
    return out


def _records_field(stats_response: dict, code: str) -> list[dict]:
    """Pull one VRM attribute series from a stats response."""
    records = (stats_response or {}).get("records") or {}
    raw = records.get(code) or []
    return _series_to_timed(raw)


def _totals_field(stats_response: dict, code: str) -> float:
    """Pull one VRM attribute total from a stats response."""
    totals = (stats_response or {}).get("totals") or {}
    return float(totals.get(code) or 0)


# ---------------------------------------------------------------------------
# Building the data block
# ---------------------------------------------------------------------------

def build_data_json(config: dict,
                     overview: dict,
                     hourly: dict,
                     daily: dict,
                     monthly: dict,
                     yearly: dict) -> dict:
    """Build data.json (without performance, that's added by write_site)."""

    # ----- Current state from system-overview --------------------------
    # VRM's system-overview structure: records.system has live values.
    ovr_records = (overview or {}).get("records") or {}
    ovr_system = ovr_records.get("system") or {}

    # Current PV power (kW) - varies by site topology, try common keys
    current_pv_kw = (ovr_system.get("solar_yield")
                      or ovr_system.get("pv_power")
                      or 0)
    if current_pv_kw:
        try:
            current_pv_kw = float(current_pv_kw) / 1000     # W -> kW
        except (TypeError, ValueError):
            current_pv_kw = 0

    # ----- Energy buckets ---------------------------------------------
    # Pull period totals - one number per period
    def bucket(stats):
        return {
            "pv":          _totals_field(stats, "Pb"),
            "consumption": _totals_field(stats, "Pc"),
            "import":      _totals_field(stats, "Gc"),
            "export":      _totals_field(stats, "Gb"),
            # Battery codes - VERIFY semantics once real data lands
            "discharge":   _totals_field(stats, "Bc"),
            "charge":      _totals_field(stats, "Bg"),
        }

    today_b   = bucket(hourly)    # hourly stats for today aggregated
    month_b   = bucket(daily)
    year_b    = bucket(monthly)
    # Lifetime: sum yearly response totals (approximation - VRM doesn't expose
    # a single "lifetime" endpoint)
    life_b    = bucket(yearly)

    # ----- Hourly time series for today --------------------------------
    pv_hourly         = _records_field(hourly, "Pb")
    consumption_hour  = _records_field(hourly, "Pc")
    import_hourly     = _records_field(hourly, "Gc")
    export_hourly     = _records_field(hourly, "Gb")
    charge_hourly     = _records_field(hourly, "Bg")
    discharge_hourly  = _records_field(hourly, "Bc")

    # ----- Status detection -------------------------------------------
    # VRM doesn't give a simple status string, so we infer from PV power
    # vs time-of-day. The dashboard layer can refine this.
    now_hr = datetime.now(tz=SAST).hour
    is_daylight = 6 <= now_hr <= 18

    if is_daylight and current_pv_kw < 0.1 and today_b["pv"] < 0.5:
        status = "underperforming"
        status_reason = "Daylight but no PV generation today"
        status_severity = "warning"
    elif not is_daylight:
        status = "offline"
        status_reason = "Outside daylight hours"
        status_severity = "info"
    elif current_pv_kw > 0.1:
        status = "online"
        status_reason = "Generating normally"
        status_severity = "ok"
    else:
        status = "unknown"
        status_reason = "Insufficient data"
        status_severity = "info"

    data = {
        "site_id": config["site_id"],
        "platform": "vrm",
        "updated_at": _sast_now_iso(),
        "current": {
            "power_kw": current_pv_kw,
            "today_kwh": today_b["pv"],
            "status": status,
            "status_severity": status_severity,
            "status_reason": status_reason,
        },
        "energy": {
            "today":    today_b,
            "month":    month_b,
            "year":     year_b,
            "lifetime": life_b,
            "hourly": {
                "pv":          pv_hourly,
                "consumption": consumption_hour,
                "import":      import_hourly,
                "export":      export_hourly,
                "charge":      charge_hourly,
                "discharge":   discharge_hourly,
            },
        },
        # Powerflow: VRM gives us the metered totals directly, so we
        # apply the per-hour split algorithm to derive directional flows.
        # Same shared module the FusionSolar processor uses.
        "energy_powerflow_hourly": _build_powerflow_hourly(
            pv_hourly, consumption_hour, import_hourly, export_hourly,
            charge_hourly, discharge_hourly,
        ),
        # Irradiation is filled in by the weather workflow - leave null here
        "irradiation": None,
        "irradiation_forecast": None,
        # Financial: only computed when tariff is configured
        "financial": None,
    }

    # Run financial computation if tariff is configured
    tariff = config.get("tariff")
    if tariff:
        data["financial"] = compute_financials(data, tariff)

    return data


def _build_powerflow_hourly(pv, consumption, imp, exp, charge, discharge):
    """For each hour we have metered values, run the V5 dual-anchor split."""
    by_time = {}
    for h in pv:           by_time.setdefault(h["time"], {})["pv"] = h["value"]
    for h in consumption:  by_time.setdefault(h["time"], {})["consumption"] = h["value"]
    for h in imp:          by_time.setdefault(h["time"], {})["import"] = h["value"]
    for h in exp:          by_time.setdefault(h["time"], {})["export"] = h["value"]
    for h in charge:       by_time.setdefault(h["time"], {})["charge"] = h["value"]
    for h in discharge:    by_time.setdefault(h["time"], {})["discharge"] = h["value"]

    out = []
    for t in sorted(by_time):
        metered = by_time[t]
        flows = powerflow.split(
            pv=metered.get("pv", 0),
            grid_import=metered.get("import", 0),
            export=metered.get("export", 0),
            charge=metered.get("charge", 0),
            discharge=metered.get("discharge", 0),
            load=metered.get("consumption", 0),
        )
        out.append({"time": t, **flows})
    return out


# ---------------------------------------------------------------------------
# History merging
# ---------------------------------------------------------------------------

def merge_history(config: dict, existing: dict | None,
                   daily_stats: dict) -> dict:
    """Rolling daily totals - keeps the last HISTORY_DAYS days."""
    days = (existing or {}).get("days", [])
    by_date = {d.get("date"): d for d in days if d.get("date")}

    # Add today's daily totals from the response
    pv_daily = _records_field(daily_stats, "Pb")
    cons_daily = _records_field(daily_stats, "Pc")
    imp_daily = _records_field(daily_stats, "Gc")
    exp_daily = _records_field(daily_stats, "Gb")

    # Index by date
    def by_date_dict(rows):
        return {r["time"].split(" ")[0]: r["value"] for r in rows}

    pv_d  = by_date_dict(pv_daily)
    co_d  = by_date_dict(cons_daily)
    im_d  = by_date_dict(imp_daily)
    ex_d  = by_date_dict(exp_daily)

    for d, v in pv_d.items():
        entry = by_date.get(d, {"date": d})
        entry["pv_kwh"]          = v
        entry["consumption_kwh"] = co_d.get(d, 0)
        entry["import_kwh"]      = im_d.get(d, 0)
        entry["export_kwh"]      = ex_d.get(d, 0)
        by_date[d] = entry

    merged = sorted(by_date.values(), key=lambda x: x.get("date", ""))
    if HISTORY_DAYS:
        merged = merged[-HISTORY_DAYS:]

    return {"site_id": config["site_id"], "days": merged}


def merge_hourly_history(config: dict, existing: dict | None,
                          data: dict) -> dict:
    """Per-hour series with metered + powerflow + irradiation fields."""
    hours = (existing or {}).get("hours", [])
    by_time = {h.get("time"): h for h in hours if h.get("time")}

    # Pull today's hourly metered values into the map
    h_pv          = (data["energy"]["hourly"].get("pv") or [])
    h_consumption = (data["energy"]["hourly"].get("consumption") or [])
    h_import      = (data["energy"]["hourly"].get("import") or [])
    h_export      = (data["energy"]["hourly"].get("export") or [])
    h_charge      = (data["energy"]["hourly"].get("charge") or [])
    h_discharge   = (data["energy"]["hourly"].get("discharge") or [])
    h_powerflow   = data.get("energy_powerflow_hourly", [])
    powerflow_by_time = {h["time"]: h for h in h_powerflow}

    def upsert(series, key):
        for entry in series:
            t = entry["time"]
            row = by_time.get(t) or {"time": t}
            row[key] = entry["value"]
            by_time[t] = row

    upsert(h_pv, "pv")
    upsert(h_consumption, "consumption")
    upsert(h_import, "import")
    upsert(h_export, "export")
    upsert(h_charge, "charge")
    upsert(h_discharge, "discharge")

    # Layer powerflow split fields on top
    for t, flows in powerflow_by_time.items():
        row = by_time.get(t) or {"time": t}
        for k, v in flows.items():
            if k != "time":
                row[k] = v
        by_time[t] = row

    merged = sorted(by_time.values(), key=lambda x: x.get("time", ""))
    # HOURLY_HISTORY_DAYS=None means unlimited retention
    if HOURLY_HISTORY_DAYS:
        cutoff = (datetime.now(tz=SAST)
                   - timedelta(days=HOURLY_HISTORY_DAYS)).strftime("%Y-%m-%d")
        merged = [h for h in merged if h.get("time", "")[:10] >= cutoff]

    return {"site_id": config["site_id"], "hours": merged}


# ---------------------------------------------------------------------------
# Top-level writer
# ---------------------------------------------------------------------------

def write_site(site_dir: Path, config: dict, *,
                overview: dict, hourly: dict, daily: dict,
                monthly: dict, yearly: dict) -> None:
    """Build and write data.json + history.json + hourly_history.json.

    Same write order as the FusionSolar processor: hourly_history before
    performance (empirical method needs history), data.json last (so it
    includes the performance block).
    """
    data = build_data_json(config, overview, hourly, daily, monthly, yearly)

    # 1. hourly_history first
    hourly_path = site_dir / "hourly_history.json"
    existing_hourly = _read_json(hourly_path)
    hourly_history = merge_hourly_history(config, existing_hourly, data)
    _write_json(hourly_path, hourly_history)

    # 2. performance block
    data["performance"] = build_performance(data, config, hourly_history)

    # 3. daily history (independent)
    history_path = site_dir / "history.json"
    existing_history = _read_json(history_path)
    history = merge_history(config, existing_history, daily)
    _write_json(history_path, history)

    # 4. data.json last, with all blocks
    _write_json(site_dir / "data.json", data)
